### PR TITLE
WIP: Combine python servers

### PR DESCRIPTION
**Pull request by jbondpk**
Work on combining python servers and other tweaks testing on Raspberry Pi.

### CODE REVIEW

**Comment by jbondpk** [comment]
@bleggett - some additional comments.

- Got it running end to end on the Pi using a prior build image.  Tested
  with reboot that node-red comes up with ServeAll.py started up.
- Found that virtualenv requirements.txt install of numpy and
  opencv-python was breaking the apt install versions, so commented out for Pi.
- Added package.json postinstall with virtualenv --system-site-packages.
  - Had to use `.` instead of `source` as default shell is dash and not
    bash forked by npm.
- Will add CAMERA_MODE (either set to picamera or opencv) option to override as discussed.

**Comment by jbondpk** [comment]
@bleggett - Sorry forgot to also add some other things noticed:

- Noticed that package.json name set to `node-red-contrib-yolo-objectdetection` instead of `node-red-contrib-yolo-object-detection` matching the repo name.  Don't know if that was intentional?
- When I tried to do a npm install directly via GitHub didn't seem to install all the required files, so just fell back to doing a git clone for now on the Pi to get it working.

**Comment by jbondpk** [comment]
@bleggett - Added the CAMERA_MODE environment variable.  Logic currently defaults to trying picamera first and then falling back to opencv unless you specify CAMERA_MODE as follows.

```
CAMERA_MODE=picamera python python-scripts/4_Serve/ServeAll.py

CAMERA_MODE=opencv python python-scripts/4_Serve/ServeAll.py
```

**Comment by bleggett** [comment]
> @bleggett - Sorry forgot to also add some other things noticed:
> 
>     * Noticed that package.json name set to `node-red-contrib-yolo-objectdetection` instead of `node-red-contrib-yolo-object-detection` matching the repo name.  Don't know if that was intentional?

Yep that's something I've corrected in another branch - will fix that.

>     * When I tried to do a npm install directly via GitHub didn't seem to install all the required files, so just fell back to doing a git clone for now on the Pi to get it working.

Same for this - I've got that.

**Comment by bleggett** [comment]
LGTM! Thanks @jbondpk

**Pull request merged**
